name: Keepalive Workflow
on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  keepalive:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: 保持工作流活跃
        uses: liskin/gh-workflow-keepalive@v1
